import streamlit as st
import pandas as pd
import pathlib
from utils.funcs import *
import plotly.express as px

# set cwd
cwd = pathlib.Path.cwd()
# streamlit page config
st.set_page_config(
    page_title='Covid-19 Dashboard Spain',
    layout = 'wide',
)
# split into sections
sections = [
    "Overview",
    "Analysis by Age Group",
    "By Province Analysis",
    "Predictions",
]
rad = st.sidebar.radio(
    "Navigation",
    sections
)
# Overview Page
if rad== "Overview":
    st.markdown("""
    # Covid-19 Dashboard For Spain
    #### *Developed By Francisco Palá*
    ***
    """)
    
    st.markdown("""
    ## Overview
    Data has been gathered from [The Ministry of Health](https://cnecovid.isciii.es/covid19/).
    The wave variable has been generated by calculating the peaks and choosing the minimum value between peaks as waves frontiers.
    """)

    if st.button('Update Data'):
        new_data = get_data()
        new_data = get_waves(get_sma7,new_data)
        new_data.to_csv(cwd / 'data/covid_19_spain.csv', sep = ';', index=False)

# read csv to process
data = pd.read_csv(cwd / 'data/covid_19_spain.csv', sep = ';')
# Time series by age group section
if rad == "Time Series By Age Group":
    st.write("""
    # Time-Series Analysis by Age Group
    The purpose of these section is to describe how 
    """)
    # process the data to plot
    age_series = get_sma7_by_age(data)
    # plot cases
    fig = px.line(
        age_series, 
        x="date", 
        y="dailyCases", 
        color='age',
        template = 'simple_white',
        width=1600,
        height=500,
        title = 'Daily Cases of Covid-19 by Age in Spain, 7-day Simple Moving Average')
    st.plotly_chart(fig, use_container_width=True)
    # plot hospitalizations
    fig = px.line(
        age_series, 
        x="date", 
        y="dailyHospitalizations", 
        color='age',
        template = 'simple_white',
        width=1600,
        height=500,
        title = 'Daily Hospitalizations of Covid-19 by Age in Spain, 7-day Simple Moving Average')
    st.plotly_chart(fig, use_container_width=True)
    # plot ICU admissions
    fig = px.line(
        age_series, 
        x="date", 
        y="dailyICU", 
        color='age',
        template = 'simple_white',
        width=1600,
        height=500,
        title = 'Daily ICU Admissions of Covid-19 by Age in Spain, 7-day Simple Moving Average')
    st.plotly_chart(fig, use_container_width=True)
    # plot deaths
    fig = px.line(
        age_series, 
        x="date", 
        y="dailyDeaths", 
        color='age',
        template = 'simple_white',
        width=1600,
        height=500,
        title = 'Daily Deaths of Covid-19 by Age in Spain, 7-day Simple Moving Average')
    st.plotly_chart(fig, use_container_width=True)

if rad == "Totals By Wave":
    st.write('Totals By Wave Section')

